const translations = {
  ru: {
    home: "Главная",
    about: "О нас",
    services: "Услуги",
    howWeWork: "Как мы работаем",
    gallery: "Галерея",
    reviews: "Отзывы",
    contact: "Контакты",
    slogan: "СОВЕРШЕНСТВО ДОСТУПНО",
    heroTitle: "Ваш гид в мире медицины Грузии",
    heroSub: "Организация лечения, трансфера и проживания «под ключ»",
    ctaConsult: "Получить консультацию",
    ourServices: "Наши услуги",
    travel: "Логистика",
    travelDesc: "Бронирование билетов и отелей",
    rhino: "Медицинские услуги",
    rhinoDesc: "Медицина Европейского уровня",
    care: "Реабилитация",
    careDesc: "Послеоперационный уход и поддержка",
    stepConsult: "Бесплатная консультация",
    stepDocs: "Сбор и перевод меддокументов",
    stepClinic: "Подбор и согласование клиники/врача",
    stepContract: "Договор, предоплата",
    stepArrival: "Прилет в Грузию (встреча в аэропорту)",
    stepTreatment: "Лечение/процедуры",
    stepRehab: "Реабилитация и досуг",
    stepSupport: "Обратная связь и поддержка после возвращения",
    conciergeService: "Консьерж-сервис",
    conciergeMeet: "Встреча и проводы в аэропорту",
    conciergeEscort: "Сопровождение и перевод на всех этапах",
    conciergeExcursions: "Бронирование экскурсий и досуга",
    conciergeHousehold: "Решение бытовых и административных вопросов",
    galleryProcedures: "Процедуры",
    galleryTourism: "Грузия для туриста",
    galleryProceduresSoon: "Скоро здесь появятся фотографии наших процедур, специалистов и клиник.",
    galleryTourismSoon: "Скоро здесь появятся лучшие виды и достопримечательности Грузии.",
    contactUs: "Свяжитесь с нами",
    orMessageUs: "Или напишите нам в мессенджер:",
    namePlaceholder: "Имя",
    emailPlaceholder: "Email",
    messagePlaceholder: "Сообщение",
    send: "Отправить",
    advantage1: "Персональный подход",
    advantage2: "Лучшие клиники Грузии",
    advantage3: "Гарантия качества",
    errorName: "Введите имя (минимум 2 буквы)",
    errorEmail: "Введите корректный email",
    errorMessage: "Сообщение слишком короткое",
    sending: "Отправка...",
    success: "Спасибо! Мы свяжемся с вами в ближайшее время.",
    missionIntro: `<strong>Миссия Med&Beauty.Ge: Совершенство доступно. Мы ваш надежный проводник к здоровью и красоте в Грузии.</strong><br><br>Мы сочетаем медицину европейского уровня с уникальным грузинским гостеприимством. Организуем все «под ключ» — от перелета до реабилитации, сотрудничая только с лучшими клиниками и специалистами. Наш приоритет — ваше комфортное, безопасное и выгодное пребывание, наполненное заботой и вниманием.`,
    mission: `“Med&Beauty Georgia” (Med&Beauty.Ge) - это мы!<br>
Мы ставим перед собой амбициозную задачу, — рассказать всему миру о Грузии не только как о Земле Гор, Вина и Моря. Но и о стране, с отличной и доступной медициной, эстетическими и бьюти услугами.<br>
Мы поддерживаем ваше стремление к здоровью и красоте — и сделаем и процесс и результат вашего путешествия безупречным опытом. Вы будете чувствовать себя в надежных руках от начала до конца.<br>
Наша команда может составить любой кейс, включая: перелет, мед. страхование, размещение, медицинские, эстетические, туристические услуги, транспортные и консьерж услуги.<br>
Мы устанавливаем высокие стандарты в медицинском туризме Грузии, сотрудничая исключительно с лучшими клиниками, проверенными врачами, высококлассными специалистами бьюти индустрии.<br>
Мы обещаем заботиться о каждом нашем госте, как о члене семьи. От первого приветствия до регистрации на обратный рейс, — наша команда будет с вами.<br>
В каждом моменте и во всех обстоятельствах вашего путешествия мы работаем на ВАШИ интересы, гарантируем комфорт и безопасность. Наши сотрудники: менеджеры, юристы, переводчики, администраторы, водители — рады помочь в любом вопросе, даже выходящем за рамки контракта.<br>
Главные приоритеты нашей работы — организовать гостям медицинские и эстетические услуги высокого качества, и обеспечить финансовую прозрачность и выгоду клиентам на всех этапах оказания услуг.<br>
С нами вам будет комфортно, безопасно и выгодно, а кроме того, — познавательно, душевно и вкусно!<br>
Ведь вы едете в Грузию!<br>
Для нас работа — это не просто турбизнес. Мы хотим, чтобы каждый гость получил не только выгодные и качественные услуги, но уезжал в свою страну, как зернышко граната, — был наполнен солнцем Грузии и теплом людей, которые здесь живут и работают.<br>
Потому что это — Грузия, а Гость в Грузии — это подарок от Бога!`,
    readMoreAbout: "Читать полностью",
    readLessAbout: "Скрыть",

    pricesNav: "Цены",
    pricesTitle: "Прайс-лист",
    pricesIntroText: "Мы предлагаем широкий спектр медицинских и косметологических услуг по конкурентоспособным ценам. Ознакомьтесь с нашим ориентировочным прайс-листом для получения более подробной информации.",
    viewDetailedPrices: "Посмотреть детальный прайс-лист",
    procedureName: "Название процедуры",
    procedurePrice: "Цена (ориентировочно)",
    priceDisclaimer: "Прайс приведен ориентировочный, не является публичной офертой, точный расчет стоимости операций и процедур будет вам выслан после онлайн консультации с врачом.",
    pricesCatEmptyPlaceholder: "Информация об услугах и ценах в этом разделе будет добавлена в ближайшее время.",

    cat_mammoplasty_nav: "Маммопластика",
    cat_legs_hips_buttocks_nav: "Операции ног, бедер, ягодиц",
    cat_arms_surgery_nav: "Операции рук",
    cat_body_surgery_nav: "Операции тела",
    cat_lipofilling_ps_nav: "Липофиллинг (ПС)",
    cat_aesthetic_gynecology_nav: "Эстетическая Гинекология",
    cat_face_neck_surgery_nav: "Операции лица и шеи",
    cat_check_up_nav: "ЧЕК-АП",
    cat_cosmetology_nav: "Косметология",
    cat_dentistry_implants_veneers_nav: "Стоматология, Имплантация, Виниры",
    cat_hair_transplant_nav: "Трансплантация Волос",
    cat_lab_tests_nav: "Лабораторные анализы",
    cat_diagnostics_nav: "Диагностика",
    cat_med_insurance_nonresident_nav: "Мед. страховка (нерезиденты)",

    cat_mammoplasty: "Маммопластика",
    cat_legs_hips_buttocks: "Операции ног, бедер, ягодиц",
    cat_arms_surgery: "Операции рук",
    cat_body_surgery: "Операции тела",
    cat_lipofilling_ps: "Липофиллинг (Пластическая хирургия)",
    cat_aesthetic_gynecology: "Эстетическая Гинекология",
    cat_face_neck_surgery: "Операции лица и шеи",
    cat_check_up: "ЧЕК-АП",
    cat_cosmetology: "Косметология",
    cat_dentistry_implants_veneers: "Стоматология, Имплантация, Виниры",
    cat_hair_transplant: "Трансплантация Волос",
    cat_lab_tests: "Лабораторные анализы",
    cat_diagnostics: "Диагностика",
    cat_med_insurance_nonresident: "Медицинская страховка для нерезидентов",

    proc_mammoplasty_augmentation: "Аугментация",
    proc_mammoplasty_periareolar_mastopexy: "Периареолярная мастопексия",
    proc_mammoplasty_t_mastopexy_no_implants: "Т образная мастопексия (без имплантов)",
    proc_mammoplasty_t_mastopexy_with_implants: "Т образная мастопексия (с имплантами)",
    proc_mammoplasty_reduction_mastopexy_1st: "Редукционная мастопексия 1 ст",
    proc_mammoplasty_implant_removal: "Удаление имплантов",
    proc_mammoplasty_reimplantation: "Реимплантация",

    proc_lhb_lipo_outer_thigh: "Липосакция внешней части бедер",
    proc_lhb_lipo_inner_thigh: "Липосакция внутренней части бедер",
    proc_lhb_lipo_knees: "Липосакция коленей",
    proc_lhb_buttock_lift: "Подтяжка ягодиц",
    proc_lhb_leg_lift: "Подтяжка ног",

    proc_arms_lipo: "Липосакции рук",
    proc_arms_lipo_armpits: "Липосакция подмышек",
    proc_arms_lift: "Подтяжка рук",

    proc_body_lipo_abdomen: "Липосакция живота",
    proc_body_liposculpture_abdomen: "Липоскульптура живота",
    proc_body_lipo_back: "Липосакция спины",
    proc_body_lipo_waist_sides: "Липосакция боков талии",
    proc_body_back_lift: "Подтяжка спины",
    proc_body_upper_abdominoplasty: "Верхняя абдоминопластика",
    proc_body_lower_abdominoplasty: "Нижняя абдоминопластика",
    proc_body_mini_abdominoplasty: "Абдоминопластика мини",

    proc_lipo_ps_1st_stage: "Липофиллинг 1 ст",
    proc_lipo_ps_2nd_stage: "Липофиллинг 2 ст",

    proc_aeg_labia_major_contouring: "Контурная пластика больших половых губ",
    proc_aeg_labiaplasty_minor: "Лабиопластика (пластика малых половых губ)",
    proc_aeg_vaginoplasty_surgical: "Вагинопластика (хирургический метод)",
    proc_aeg_vaginal_correction_aptos: "Коррекция влагалища (восстановление стенок) нитями aptos",
    proc_aeg_labia_major_lipofilling: "Липофилинг больших половых губ",
    proc_aeg_g_spot_augmentation_filler: "Увеличения точки G филлером (цена за 1 шприц)",
    proc_aeg_incontinence_threads: "Лечение недержание мочи (нити)",
    proc_aeg_sensitivity_enhancement_procedure: "Процедура для увеличения чувствительности",
    proc_aeg_intimate_whitening_peel: "Отбеливание (Пилинг интимной зоны)",
    
    proc_fn_endo_lift_upper_2_3: "Эндоскопическая подтяжка верхних 2/3 лица",
    proc_fn_endo_lift_mid_face: "Эндоскопическая подтяжка средней трети лица",
    proc_fn_anterior_medial_platysmaplasty: "Передняя (медиальная) платизмопластика",
    proc_fn_otoplasty_bilateral_combo: "Отопластика с двух сторон (в комбинации)",
    proc_fn_otoplasty_bilateral_complex_combo: "Отопластика с двух сторон (сложная деформация) (в комбинации)",
    proc_fn_otoplasty_unilateral_combo: "Отопластика с одной стороны (в комбинации)",
    proc_fn_earlobe_correction_unilateral_proc: "Коррекция мочки уха с одной стороны (в процедурной)",
    proc_fn_upper_lip_plasty_combo: "Пластика верхней губы (Хейлопластика, Булхорн, Кисельринг, V-Y пластика) (в комбинации)",
    proc_fn_upper_lip_lift_corner: "Пластика верхней губы (корнерлифт)",
    proc_fn_bichat_fat_pad_removal_combo: "Резекция комков Биша (в комбинации)",
    proc_fn_facial_lipofilling_paired_zone_proc: "Липофиллинг лица (парная зона) (в процедурной)",
    proc_fn_upper_bleph_proc: "Верхняя блефаропластика (в процедурной)",
    proc_fn_lower_bleph_combo: "Нижняя блефаропластика (в комбинации)",
    proc_fn_lower_bleph_fat_redistribution: "Нижняя блефаропластика с жирораспределением",
    proc_fn_lower_bleph_transconj_fat_redist: "Нижняя блефаропластика трансконъюктивальная (с жирораспределением)",
    proc_fn_asian_eyelid_plasty_upper_combo: "Пластика азиатских век (верхние) (в комбинации)",
    proc_fn_upper_lower_bleph: "Верхняя и нижняя блефаропластика",
    proc_fn_upper_lower_bleph_fat_redist: "Верхняя и нижняя блефаропластика с жирораспределением",
    proc_fn_canthopexy_combo: "Кантопексия (в комбинации)",
    proc_fn_cheek_lift_mid_face: "Чек-лифт (подтяжка средней трети лица)",
    proc_fn_smas_lift_lower_face_neck: "SMAS-лифтинг лица (нижняя треть) и шеи",
    proc_fn_smas_lift_post_threads_fillers: "SMAS-лифтинг лица (нижняя треть) и шеи: после раннее установленных нитей, филлеров, аппаратного SMAS-лифтинга",
    proc_fn_smas_lift_revision: "SMAS-лифтинг лица и шеи повторный",
    proc_fn_endo_forehead_lift: "Эндоскопическая подтяжка лба",
    proc_fn_endo_temporal_lift: "Эндоскопическая подтяжка височной области",
    proc_fn_open_forehead_lift: "Пластика лба открытым способом",
    proc_fn_chin_lipo_submental_proc: "Липосакция подбородка (субментальной зоны)(в процедурной)",
    proc_fn_rhinoplasty: "Ринопластика",
    proc_fn_mentoplasty_no_implant: "Ментопластика (без стоимости импланта)",
    proc_fn_mentoplasty_local_tissues: "Ментопластика с использованием местных тканей",

    proc_checkup_male: "мужской",
    proc_checkup_female: "женский",
    proc_checkup_child: "детский",
    proc_checkup_express: "экспресс чекап",

    proc_cosm_lip_augmentation_korea: "Увеличение губ (Корея)",
    proc_cosm_lip_augmentation_europe: "Увеличение губ (Европейские препараты)",
    proc_cosm_biorevitalization: "Биоревитализация",
    proc_cosm_polylactic_acid: "Полимолочная кислота",
    proc_cosm_mesotherapy: "Мезотерапия",
    proc_cosm_lifting_threfill: "Лифтинг препарат Threfill",
    proc_cosm_collagen_karisma_900: "Коллаген Кarisma 900",
    proc_cosm_long_lasting_volume: "Long lasting (воссоздание обьема)",
    proc_cosm_lipolytics: "Липолитики",
    proc_cosm_fillers: "Филлеры",
    proc_cosm_hands_rejuvenation: "Руки (омоложение)",
    proc_cosm_botox_one_zone: "Ботокс, одна зона",
    proc_cosm_botox_full_face: "Ботокс Full face",
    proc_cosm_neck_decollete_rejuvenation: "Шея, декольте (омоложение) в зависимости от выбранной методики и препарата",
    proc_cosm_chin_correction: "Коррекция подбородка",
    proc_cosm_calcium_hydroxyapatite_radiess: "Гидроксиапатит кальция Radiess",
    proc_cosm_boosters: "Бустеры",
    proc_cosm_polynucleotides: "Полинуклеотиды",
    proc_cosm_scalp_mesotherapy: "Мезотерапия головы",
    proc_cosm_hyperhidrosis_botox: "Лечение гипергидроза ботоксом",
    proc_cosm_plasma_shower: "Плазменный душ",
    proc_cosm_collagen_under_eye_infini: "Коллаген для зоны под глаза италия infini",
    proc_cosm_exosomes_jeuderm: "Екзосомы Jeuderm",

    proc_medins_60_coverage_yearly: "с покрытием 60%, стоимость за год",
    proc_medins_90_coverage_yearly: "с покрытием 90%, стоимость за год",

  },
  en: { // Placeholders - please translate these from Russian above
    home: "Home",
    about: "About Us",
    services: "Services",
    howWeWork: "How We Work",
    gallery: "Gallery",
    reviews: "Reviews",
    contact: "Contacts",
    slogan: "PERFECTION AVAILABLE",
    heroTitle: "Your Guide to Georgian Medicine",
    heroSub: "Complete organization of treatment, transfer, and accommodation",
    ctaConsult: "Get a Consultation",
    ourServices: "Our Services",
    travel: "Travel Logistics",
    travelDesc: "Booking tickets and hotels",
    rhino: "Medical Services",
    rhinoDesc: "European-level healthcare",
    care: "Rehabilitation",
    careDesc: "Post-operative care and support",
    stepConsult: "Free consultation",
    stepDocs: "Collection and translation of medical documents",
    stepClinic: "Selection and agreement of clinic/doctor",
    stepContract: "Contract, prepayment",
    stepArrival: "Arrival to Georgia (airport pick-up)",
    stepTreatment: "Treatment/procedures",
    stepRehab: "Rehabilitation and leisure",
    stepSupport: "Feedback and support after returning home",
    conciergeService: "Concierge Service",
    conciergeMeet: "Meeting and seeing off at the airport",
    conciergeEscort: "Escort and translation at all stages",
    conciergeExcursions: "Booking excursions and leisure",
    conciergeHousehold: "Solving household and administrative issues",
    galleryProcedures: "Procedures",
    galleryTourism: "Georgia for Tourists",
    galleryProceduresSoon: "Soon you will see photos of our procedures, specialists, and clinics here.",
    galleryTourismSoon: "Soon you will see the best views and attractions of Georgia here.",
    contactUs: "Contact Us",
    orMessageUs: "Or write to us in messenger:",
    namePlaceholder: "Name",
    emailPlaceholder: "Email",
    messagePlaceholder: "Message",
    send: "Send",
    advantage1: "Personal approach",
    advantage2: "Best clinics in Georgia",
    advantage3: "Quality guarantee",
    errorName: "Enter your name (at least 2 letters)",
    errorEmail: "Enter a valid email",
    errorMessage: "Message is too short",
    sending: "Sending...",
    success: "Thank you! We will contact you soon.",
    missionIntro: `<strong>Med&Beauty.Ge Mission: Perfection is available. We are your reliable guide to health and beauty in Georgia.</strong><br><br>We combine European-level medicine with unique Georgian hospitality. We organize everything "turnkey" – from flights to rehabilitation, cooperating only with the best clinics and specialists. Our priority is your comfortable, safe, and beneficial stay, filled with care and attention.`,
    mission: `“Med&Beauty Georgia” (Med&Beauty.Ge) is us!<br>
Our ambitious goal is to tell the world about Georgia not only as a land of mountains, wine, and sea, but also as a country with excellent and affordable healthcare, aesthetics, and beauty services.<br>
We support your desire for health and beauty—and will make both the process and the result of your trip a perfect experience. You will feel in safe hands from start to finish.<br>
Our team can assemble any case, including: flight, medical insurance, accommodation, medical, aesthetic, tourist, transport and concierge services.<br>
We set high standards in Georgian medical tourism, working exclusively with the best clinics, trusted doctors, and top beauty specialists.<br>
We promise to care for every guest as a family member. From the first greeting to the return flight check-in, our team is with you.<br>
At every moment and in all circumstances of your trip, we act in YOUR interests, guaranteeing comfort and safety. Our staff: managers, lawyers, translators, administrators, drivers—are happy to help with any question, even beyond the contract.<br>
Our main priorities are to organize guests high-quality medical and aesthetic services, and to provide financial transparency and benefit to clients at all stages.<br>
With us, you will be comfortable, safe, and profitable, and in addition—enlightened, soulful, and well-fed!<br>
Because you are going to Georgia!<br>
For us, work is not just a tourism business. We want every guest not only to receive favorable and high-quality services, but to leave Georgia filled with its sun and the warmth of its people.<br>
Because this is Georgia, and a guest in Georgia is a gift from God!`,
    readMoreAbout: "Read More",
    readLessAbout: "Read Less",
    pricesNav: "Prices",
    pricesTitle: "Price List",
    pricesIntroText: "We offer a wide range of medical and cosmetology services at competitive prices. Check out our indicative price list for more detailed information.",
    viewDetailedPrices: "View Detailed Price List",
    procedureName: "Procedure Name",
    procedurePrice: "Approx. Price",
    priceDisclaimer: "The price list is indicative and does not constitute a public offer. The exact cost of operations and procedures will be sent to you after an online consultation with a doctor.",
    pricesCatEmptyPlaceholder: "Information about services and prices in this section will be added soon.",
    cat_mammoplasty_nav: "Mammoplasty",
    cat_legs_hips_buttocks_nav: "Leg, Hip, Buttock Surgery",
    cat_arms_surgery_nav: "Arm Surgery",
    cat_body_surgery_nav: "Body Surgery",
    cat_lipofilling_ps_nav: "Lipofilling (PS)",
    cat_aesthetic_gynecology_nav: "Aesthetic Gynecology",
    cat_face_neck_surgery_nav: "Face & Neck Surgery",
    cat_check_up_nav: "CHECK-UP",
    cat_cosmetology_nav: "Cosmetology",
    cat_dentistry_implants_veneers_nav: "Dentistry, Implants, Veneers",
    cat_hair_transplant_nav: "Hair Transplant",
    cat_lab_tests_nav: "Lab Tests",
    cat_diagnostics_nav: "Diagnostics",
    cat_med_insurance_nonresident_nav: "Medical Insurance (Non-residents)",
    cat_mammoplasty: "Mammoplasty",
    cat_legs_hips_buttocks: "Leg, Hip, Buttock Surgery",
    cat_arms_surgery: "Arm Surgery",
    cat_body_surgery: "Body Surgery",
    cat_lipofilling_ps: "Lipofilling (Plastic Surgery)",
    cat_aesthetic_gynecology: "Aesthetic Gynecology",
    cat_face_neck_surgery: "Face & Neck Surgery",
    cat_check_up: "CHECK-UP",
    cat_cosmetology: "Cosmetology",
    cat_dentistry_implants_veneers: "Dentistry, Implants, Veneers",
    cat_hair_transplant: "Hair Transplant",
    cat_lab_tests: "Lab Tests",
    cat_diagnostics: "Diagnostics",
    cat_med_insurance_nonresident: "Medical Insurance for Non-residents",
    proc_mammoplasty_augmentation: "Augmentation",
    proc_mammoplasty_periareolar_mastopexy: "Periareolar Mastopexy",
    proc_mammoplasty_t_mastopexy_no_implants: "T-scar Mastopexy (no implants)",
    proc_mammoplasty_t_mastopexy_with_implants: "T-scar Mastopexy (with implants)",
    proc_mammoplasty_reduction_mastopexy_1st: "Reduction Mastopexy (1st stage)",
    proc_mammoplasty_implant_removal: "Implant Removal",
    proc_mammoplasty_reimplantation: "Reimplantation",
    proc_lhb_lipo_outer_thigh: "Outer Thigh Liposuction",
    proc_lhb_lipo_inner_thigh: "Inner Thigh Liposuction",
    proc_lhb_lipo_knees: "Knee Liposuction",
    proc_lhb_buttock_lift: "Buttock Lift",
    proc_lhb_leg_lift: "Leg Lift",
    proc_arms_lipo: "Arm Liposuction",
    proc_arms_lipo_armpits: "Armpit Liposuction",
    proc_arms_lift: "Arm Lift",
    proc_body_lipo_abdomen: "Abdomen Liposuction",
    proc_body_liposculpture_abdomen: "Abdomen Liposculpture",
    proc_body_lipo_back: "Back Liposuction",
    proc_body_lipo_waist_sides: "Waist Sides Liposuction",
    proc_body_back_lift: "Back Lift",
    proc_body_upper_abdominoplasty: "Upper Abdominoplasty",
    proc_body_lower_abdominoplasty: "Lower Abdominoplasty",
    proc_body_mini_abdominoplasty: "Mini Abdominoplasty",
    proc_lipo_ps_1st_stage: "Lipofilling (1st stage)",
    proc_lipo_ps_2nd_stage: "Lipofilling (2nd stage)",
    proc_aeg_labia_major_contouring: "Labia Majora Contouring",
    proc_aeg_labiaplasty_minor: "Labiaplasty (Labia Minora)",
    proc_aeg_vaginoplasty_surgical: "Vaginoplasty (surgical method)",
    proc_aeg_vaginal_correction_aptos: "Vaginal Wall Correction (Aptos threads)",
    proc_aeg_labia_major_lipofilling: "Labia Majora Lipofilling",
    proc_aeg_g_spot_augmentation_filler: "G-Spot Augmentation (filler, per syringe)",
    proc_aeg_incontinence_threads: "Urinary Incontinence Treatment (threads)",
    proc_aeg_sensitivity_enhancement_procedure: "Sensitivity Enhancement Procedure",
    proc_aeg_intimate_whitening_peel: "Intimate Area Whitening (Peel)",
    proc_fn_endo_lift_upper_2_3: "Endoscopic Upper 2/3 Face Lift",
    proc_fn_endo_lift_mid_face: "Endoscopic Midface Lift",
    proc_fn_anterior_medial_platysmaplasty: "Anterior (Medial) Platysmaplasty",
    proc_fn_otoplasty_bilateral_combo: "Otoplasty, Bilateral (in combination)",
    proc_fn_otoplasty_bilateral_complex_combo: "Otoplasty, Bilateral, Complex Deformity (in combination)",
    proc_fn_otoplasty_unilateral_combo: "Otoplasty, Unilateral (in combination)",
    proc_fn_earlobe_correction_unilateral_proc: "Earlobe Correction, Unilateral (in-office)",
    proc_fn_upper_lip_plasty_combo: "Upper Lip Plasty (Cheiloplasty, Bullhorn, Kisselring, V-Y) (in combination)",
    proc_fn_upper_lip_lift_corner: "Upper Lip Corner Lift",
    proc_fn_bichat_fat_pad_removal_combo: "Buccal Fat Pad Removal (in combination)",
    proc_fn_facial_lipofilling_paired_zone_proc: "Facial Lipofilling, Paired Zone (in-office)",
    proc_fn_upper_bleph_proc: "Upper Blepharoplasty (in-office)",
    proc_fn_lower_bleph_combo: "Lower Blepharoplasty (in combination)",
    proc_fn_lower_bleph_fat_redistribution: "Lower Blepharoplasty with Fat Redistribution",
    proc_fn_lower_bleph_transconj_fat_redist: "Lower Blepharoplasty, Transconjunctival (with fat redistribution)",
    proc_fn_asian_eyelid_plasty_upper_combo: "Asian Eyelid Plasty, Upper (in combination)",
    proc_fn_upper_lower_bleph: "Upper and Lower Blepharoplasty",
    proc_fn_upper_lower_bleph_fat_redist: "Upper and Lower Blepharoplasty with Fat Redistribution",
    proc_fn_canthopexy_combo: "Canthopexy (in combination)",
    proc_fn_cheek_lift_mid_face: "Cheek Lift (Midface Lift)",
    proc_fn_smas_lift_lower_face_neck: "SMAS Lift, Lower Face and Neck",
    proc_fn_smas_lift_post_threads_fillers: "SMAS Lift, Lower Face and Neck (after previous threads, fillers, SMAS lifting)",
    proc_fn_smas_lift_revision: "SMAS Lift, Face and Neck, Revision",
    proc_fn_endo_forehead_lift: "Endoscopic Forehead Lift",
    proc_fn_endo_temporal_lift: "Endoscopic Temporal Lift",
    proc_fn_open_forehead_lift: "Open Forehead Lift",
    proc_fn_chin_lipo_submental_proc: "Chin Liposuction (Submental Area) (in-office)",
    proc_fn_rhinoplasty: "Rhinoplasty",
    proc_fn_mentoplasty_no_implant: "Mentoplasty (without implant cost)",
    proc_fn_mentoplasty_local_tissues: "Mentoplasty with Local Tissues",
    proc_checkup_male: "Male Check-up",
    proc_checkup_female: "Female Check-up",
    proc_checkup_child: "Child Check-up",
    proc_checkup_express: "Express Check-up",
    proc_cosm_lip_augmentation_korea: "Lip Augmentation (Korea)",
    proc_cosm_lip_augmentation_europe: "Lip Augmentation (European products)",
    proc_cosm_biorevitalization: "Biorevitalization",
    proc_cosm_polylactic_acid: "Polylactic Acid",
    proc_cosm_mesotherapy: "Mesotherapy",
    proc_cosm_lifting_threfill: "Threfill Lifting",
    proc_cosm_collagen_karisma_900: "Collagen Karisma 900",
    proc_cosm_long_lasting_volume: "Long Lasting (Volume Restoration)",
    proc_cosm_lipolytics: "Lipolytics",
    proc_cosm_fillers: "Fillers",
    proc_cosm_hands_rejuvenation: "Hand Rejuvenation",
    proc_cosm_botox_one_zone: "Botox, One Zone",
    proc_cosm_botox_full_face: "Botox, Full Face",
    proc_cosm_neck_decollete_rejuvenation: "Neck, Décolleté Rejuvenation (depends on method and product)",
    proc_cosm_chin_correction: "Chin Correction",
    proc_cosm_calcium_hydroxyapatite_radiess: "Calcium Hydroxyapatite (Radiess)",
    proc_cosm_boosters: "Boosters",
    proc_cosm_polynucleotides: "Polynucleotides",
    proc_cosm_scalp_mesotherapy: "Scalp Mesotherapy",
    proc_cosm_hyperhidrosis_botox: "Hyperhidrosis Treatment (Botox)",
    proc_cosm_plasma_shower: "Plasma Shower",
    proc_cosm_collagen_under_eye_infini: "Collagen for Under Eye Area (Infini, Italy)",
    proc_cosm_exosomes_jeuderm: "Exosomes (Jeuderm)",
    proc_medins_60_coverage_yearly: "60% Coverage, Annual Cost",
    proc_medins_90_coverage_yearly: "90% Coverage, Annual Cost",
  },
  de: { // Placeholders - please translate these from Russian above
    home: "Startseite",
    about: "Über uns",
    services: "Leistungen",
    howWeWork: "So arbeiten wir",
    gallery: "Galerie",
    reviews: "Bewertungen",
    contact: "Kontakt",
    slogan: "PERFEKTION IST ERREICHBAR",
    heroTitle: "Ihr Leitfaden für georgische Medizin",
    heroSub: "Organisation von Behandlung, Transfer und Unterkunft „aus einer Hand“",
    ctaConsult: "Beratung anfordern",
    ourServices: "Unsere Leistungen",
    travel: "Reiselogistik",
    travelDesc: "Buchung von Tickets und Hotels",
    rhino: "Medizinische Leistungen",
    rhinoDesc: "Medizin auf europäischem Niveau",
    care: "Rehabilitation",
    careDesc: "Nachsorge und Unterstützung",
    stepConsult: "Kostenlose Beratung",
    stepDocs: "Sammlung und Übersetzung von medizinischen Unterlagen",
    stepClinic: "Auswahl und Abstimmung der Klinik/des Arztes",
    stepContract: "Vertrag, Anzahlung",
    stepArrival: "Ankunft in Georgien (Abholung am Flughafen)",
    stepTreatment: "Behandlung/Prozeduren",
    stepRehab: "Rehabilitation und Freizeit",
    stepSupport: "Feedback und Unterstützung nach der Rückkehr",
    conciergeService: "Concierge-Service",
    conciergeMeet: "Abholung und Verabschiedung am Flughafen",
    conciergeEscort: "Begleitung und Übersetzung in allen Phasen",
    conciergeExcursions: "Buchung von Ausflügen und Freizeitaktivitäten",
    conciergeHousehold: "Lösung von Alltags- und Verwaltungsfragen",
    galleryProcedures: "Prozeduren",
    galleryTourism: "Georgien für Touristen",
    galleryProceduresSoon: "Hier erscheinen bald Fotos unserer Prozeduren, Spezialisten und Kliniken.",
    galleryTourismSoon: "Hier erscheinen bald die schönsten Ansichten und Sehenswürdigkeiten Georgiens.",
    contactUs: "Kontaktieren Sie uns",
    orMessageUs: "Oder schreiben Sie uns im Messenger:",
    namePlaceholder: "Name",
    emailPlaceholder: "E-Mail",
    messagePlaceholder: "Nachricht",
    send: "Senden",
    advantage1: "Individueller Ansatz",
    advantage2: "Beste Kliniken Georgiens",
    advantage3: "Qualitätsgarantie",
    errorName: "Geben Sie Ihren Namen ein (mindestens 2 Buchstaben)",
    errorEmail: "Gültige E-Mail eingeben",
    errorMessage: "Nachricht ist zu kurz",
    sending: "Senden...",
    success: "Vielen Dank! Wir melden uns bald.",
    missionIntro: `<strong>Mission Med&Beauty.Ge: Perfektion ist erreichbar. Wir sind Ihr zuverlässiger Führer zu Gesundheit und Schönheit in Georgien.</strong><br><br>Wir verbinden Medizin auf europäischem Niveau mit einzigartiger georgischer Gastfreundschaft. Wir organisieren alles „schlüsselfertig“ – von Flügen bis zur Rehabilitation, in Zusammenarbeit nur mit den besten Kliniken und Spezialisten. Unsere Priorität ist Ihr komfortabler, sicherer und vorteilhafter Aufenthalt, erfüllt von Sorgfalt und Aufmerksamkeit.`,
    mission: `„Med&Beauty Georgia“ (Med&Beauty.Ge) – das sind wir!<br>
Unser Ziel ist es, der Welt nicht nur Georgien als Land der Berge, des Weins und des Meeres vorzustellen, sondern auch als Land mit ausgezeichneter und erschwinglicher Medizin, Ästhetik und Beauty-Dienstleistungen.<br>
Wir unterstützen Ihr Streben nach Gesundheit und Schönheit – und machen sowohl den Prozess als auch das Ergebnis Ihrer Reise zu einem perfekten Erlebnis. Sie werden sich von Anfang bis Ende in sicheren Händen fühlen.<br>
Unser Team stellt jeden Fall individuell zusammen, inkl. Flug, Krankenversicherung, Unterkunft, medizinische, ästhetische, touristische, Transport- und Concierge-Leistungen.<br>
Wir setzen hohe Standards im medizinischen Tourismus Georgiens, arbeiten nur mit den besten Kliniken, bewährten Ärzten und Top-Spezialisten zusammen.<br>
Wir kümmern uns um jeden Gast wie um ein Familienmitglied. Vom ersten Kontakt bis zum Rückflug ist unser Team an Ihrer Seite.<br>
In jedem Moment und unter allen Umständen arbeiten wir in IHREM Interesse, garantieren Komfort und Sicherheit. Unsere Mitarbeiter: Manager, Juristen, Übersetzer, Administratoren, Fahrer – helfen gerne bei jeder Frage, auch außerhalb des Vertrags.<br>
Unsere Hauptprioritäten sind: medizinische und ästhetische Leistungen höchster Qualität und finanzielle Transparenz und Vorteil für unsere Kunden in allen Phasen.<br>
Mit uns wird Ihre Reise komfortabel, sicher und lohnend – außerdem lehrreich, herzlich und köstlich!<br>
Sie reisen nach Georgien!<br>
Für uns ist es nicht nur Tourismus. Wir möchten, dass jeder Gast nicht nur hochwertige und günstige Leistungen erhält, sondern mit Sonne und Wärme Georgiens abreist.<br>
Denn das ist Georgien, und der Gast in Georgien ist ein Geschenk Gottes!`,
    readMoreAbout: "Mehr lesen",
    readLessAbout: "Weniger anzeigen",
    pricesNav: "Preise",
    pricesTitle: "Preisliste",
    pricesIntroText: "Wir bieten eine breite Palette von medizinischen und kosmetologischen Dienstleistungen zu wettbewerbsfähigen Preisen an. Sehen Sie sich unsere Richtpreisliste für detailliertere Informationen an.",
    viewDetailedPrices: "Detaillierte Preisliste ansehen",
    procedureName: "Verfahrensname",
    procedurePrice: "Ca. Preis",
    priceDisclaimer: "Die Preisliste ist Richtwert und stellt kein öffentliches Angebot dar. Die genauen Kosten für Operationen und Eingriffe werden Ihnen nach einer Online-Konsultation mit einem Arzt zugesandt.",
    pricesCatEmptyPlaceholder: "Informationen zu Dienstleistungen und Preisen in diesem Abschnitt werden in Kürze hinzugefügt.",
    cat_mammoplasty_nav: "Mammoplastik",
    cat_legs_hips_buttocks_nav: "Bein-, Hüft-, Gesäßchirurgie",
    cat_arms_surgery_nav: "Armchirurgie",
    cat_body_surgery_nav: "Körperchirurgie",
    cat_lipofilling_ps_nav: "Lipofilling (PC)",
    cat_aesthetic_gynecology_nav: "Ästhetische Gynäkologie",
    cat_face_neck_surgery_nav: "Gesichts- & Halschirurgie",
    cat_check_up_nav: "CHECK-UP",
    cat_cosmetology_nav: "Kosmetologie",
    cat_dentistry_implants_veneers_nav: "Zahnmedizin, Implantate, Veneers",
    cat_hair_transplant_nav: "Haartransplantation",
    cat_lab_tests_nav: "Labortests",
    cat_diagnostics_nav: "Diagnostik",
    cat_med_insurance_nonresident_nav: "Krankenversicherung (Nichtansässige)",
    cat_mammoplasty: "Mammoplastik",
    cat_legs_hips_buttocks: "Bein-, Hüft-, Gesäßchirurgie",
    cat_arms_surgery: "Armchirurgie",
    cat_body_surgery: "Körperchirurgie",
    cat_lipofilling_ps: "Lipofilling (Plastische Chirurgie)",
    cat_aesthetic_gynecology: "Ästhetische Gynäkologie",
    cat_face_neck_surgery: "Gesichts- & Halschirurgie",
    cat_check_up: "CHECK-UP",
    cat_cosmetology: "Kosmetologie",
    cat_dentistry_implants_veneers: "Zahnmedizin, Implantate, Veneers",
    cat_hair_transplant: "Haartransplantation",
    cat_lab_tests: "Labortests",
    cat_diagnostics: "Diagnostik",
    cat_med_insurance_nonresident: "Krankenversicherung für Nichtansässige",
    proc_mammoplasty_augmentation: "Augmentation",
    proc_mammoplasty_periareolar_mastopexy: "Periareoläre Mastopexie",
    proc_mammoplasty_t_mastopexy_no_implants: "T-Narben-Mastopexie (ohne Implantate)",
    proc_mammoplasty_t_mastopexy_with_implants: "T-Narben-Mastopexie (mit Implantaten)",
    proc_mammoplasty_reduction_mastopexy_1st: "Reduktionsmastopexie (1. Stufe)",
    proc_mammoplasty_implant_removal: "Implantatentfernung",
    proc_mammoplasty_reimplantation: "Reimplantation",
    proc_lhb_lipo_outer_thigh: "Liposuktion der äußeren Oberschenkel",
    proc_lhb_lipo_inner_thigh: "Liposuktion der inneren Oberschenkel",
    proc_lhb_lipo_knees: "Knie-Liposuktion",
    proc_lhb_buttock_lift: "Gesäßstraffung",
    proc_lhb_leg_lift: "Beinstraffung",
    proc_arms_lipo: "Arm-Liposuktion",
    proc_arms_lipo_armpits: "Achselhöhlen-Liposuktion",
    proc_arms_lift: "Armstraffung",
    proc_body_lipo_abdomen: "Bauch-Liposuktion",
    proc_body_liposculpture_abdomen: "Bauch-Liposkulptur",
    proc_body_lipo_back: "Rücken-Liposuktion",
    proc_body_lipo_waist_sides: "Taillen-Seiten-Liposuktion",
    proc_body_back_lift: "Rückenstraffung",
    proc_body_upper_abdominoplasty: "Obere Bauchdeckenstraffung",
    proc_body_lower_abdominoplasty: "Untere Bauchdeckenstraffung",
    proc_body_mini_abdominoplasty: "Mini-Bauchdeckenstraffung",
    proc_lipo_ps_1st_stage: "Lipofilling (1. Stufe)",
    proc_lipo_ps_2nd_stage: "Lipofilling (2. Stufe)",
    proc_aeg_labia_major_contouring: "Konturierung der großen Schamlippen",
    proc_aeg_labiaplasty_minor: "Labiaplastik (kleine Schamlippen)",
    proc_aeg_vaginoplasty_surgical: "Vaginoplastik (chirurgische Methode)",
    proc_aeg_vaginal_correction_aptos: "Vaginalwandkorrektur (Aptos-Fäden)",
    proc_aeg_labia_major_lipofilling: "Lipofilling der großen Schamlippen",
    proc_aeg_g_spot_augmentation_filler: "G-Punkt-Augmentation (Filler, pro Spritze)",
    proc_aeg_incontinence_threads: "Behandlung von Harninkontinenz (Fäden)",
    proc_aeg_sensitivity_enhancement_procedure: "Verfahren zur Sensibilitätssteigerung",
    proc_aeg_intimate_whitening_peel: "Intimaufhellung (Peeling)",
    proc_fn_endo_lift_upper_2_3: "Endoskopisches oberes 2/3 Gesichtslifting",
    proc_fn_endo_lift_mid_face: "Endoskopisches Mittelgesichtslifting",
    proc_fn_anterior_medial_platysmaplasty: "Anteriore (mediale) Platysmaplastik",
    proc_fn_otoplasty_bilateral_combo: "Otoplastik, beidseitig (in Kombination)",
    proc_fn_otoplasty_bilateral_complex_combo: "Otoplastik, beidseitig, komplexe Deformität (in Kombination)",
    proc_fn_otoplasty_unilateral_combo: "Otoplastik, einseitig (in Kombination)",
    proc_fn_earlobe_correction_unilateral_proc: "Ohrläppchenkorrektur, einseitig (ambulant)",
    proc_fn_upper_lip_plasty_combo: "Oberlippenplastik (Cheiloplastik, Bullhorn, Kisselring, V-Y) (in Kombination)",
    proc_fn_upper_lip_lift_corner: "Oberlippen-Eckenlift",
    proc_fn_bichat_fat_pad_removal_combo: "Entfernung der Bichat'schen Fettpolster (in Kombination)",
    proc_fn_facial_lipofilling_paired_zone_proc: "Gesichts-Lipofilling, paarige Zone (ambulant)",
    proc_fn_upper_bleph_proc: "Obere Blepharoplastik (ambulant)",
    proc_fn_lower_bleph_combo: "Untere Blepharoplastik (in Kombination)",
    proc_fn_lower_bleph_fat_redistribution: "Untere Blepharoplastik mit Fettumverteilung",
    proc_fn_lower_bleph_transconj_fat_redist: "Untere Blepharoplastik, transkonjunktival (mit Fettumverteilung)",
    proc_fn_asian_eyelid_plasty_upper_combo: "Asiatische Lidplastik, obere (in Kombination)",
    proc_fn_upper_lower_bleph: "Obere und untere Blepharoplastik",
    proc_fn_upper_lower_bleph_fat_redist: "Obere und untere Blepharoplastik mit Fettumverteilung",
    proc_fn_canthopexy_combo: "Kanthopexie (in Kombination)",
    proc_fn_cheek_lift_mid_face: "Wangenlifting (Mittelgesichtslifting)",
    proc_fn_smas_lift_lower_face_neck: "SMAS-Lifting, unteres Gesicht und Hals",
    proc_fn_smas_lift_post_threads_fillers: "SMAS-Lifting, unteres G. u. H. (nach früheren Fäden, Fillern, SMAS-Lifting)",
    proc_fn_smas_lift_revision: "SMAS-Lifting, Gesicht und Hals, Revision",
    proc_fn_endo_forehead_lift: "Endoskopisches Stirnlifting",
    proc_fn_endo_temporal_lift: "Endoskopisches Schläfenlifting",
    proc_fn_open_forehead_lift: "Offenes Stirnlifting",
    proc_fn_chin_lipo_submental_proc: "Kinn-Liposuktion (Submentalbereich) (ambulant)",
    proc_fn_rhinoplasty: "Rhinoplastik",
    proc_fn_mentoplasty_no_implant: "Mentoplastik (ohne Implantatkosten)",
    proc_fn_mentoplasty_local_tissues: "Mentoplastik mit lokalen Geweben",
    proc_checkup_male: "Männer-Check-up",
    proc_checkup_female: "Frauen-Check-up",
    proc_checkup_child: "Kinder-Check-up",
    proc_checkup_express: "Express-Check-up",
    proc_cosm_lip_augmentation_korea: "Lippenvergrößerung (Korea)",
    proc_cosm_lip_augmentation_europe: "Lippenvergrößerung (Europäische Produkte)",
    proc_cosm_biorevitalization: "Biorevitalisierung",
    proc_cosm_polylactic_acid: "Polymilchsäure",
    proc_cosm_mesotherapy: "Mesotherapie",
    proc_cosm_lifting_threfill: "Threfill Lifting",
    proc_cosm_collagen_karisma_900: "Kollagen Karisma 900",
    proc_cosm_long_lasting_volume: "Long Lasting (Volumenwiederherstellung)",
    proc_cosm_lipolytics: "Lipolytika",
    proc_cosm_fillers: "Filler",
    proc_cosm_hands_rejuvenation: "Handverjüngung",
    proc_cosm_botox_one_zone: "Botox, eine Zone",
    proc_cosm_botox_full_face: "Botox, ganzes Gesicht",
    proc_cosm_neck_decollete_rejuvenation: "Hals-, Dekolleté-Verjüngung (je nach Methode und Produkt)",
    proc_cosm_chin_correction: "Kinnkorrektur",
    proc_cosm_calcium_hydroxyapatite_radiess: "Calciumhydroxylapatit (Radiess)",
    proc_cosm_boosters: "Booster",
    proc_cosm_polynucleotides: "Polynukleotide",
    proc_cosm_scalp_mesotherapy: "Kopfhaut-Mesotherapie",
    proc_cosm_hyperhidrosis_botox: "Behandlung von Hyperhidrose (Botox)",
    proc_cosm_plasma_shower: "Plasma-Dusche",
    proc_cosm_collagen_under_eye_infini: "Kollagen für die Augenpartie (Infini, Italien)",
    proc_cosm_exosomes_jeuderm: "Exosomen (Jeuderm)",
    proc_medins_60_coverage_yearly: "60% Deckung, jährliche Kosten",
    proc_medins_90_coverage_yearly: "90% Deckung, jährliche Kosten",
  }
};

window.translations = translations; 

function applyTranslations(lang) {
    document.documentElement.setAttribute('lang', lang);
    document.querySelectorAll('.lang-switcher button').forEach(btn => {
        btn.classList.remove('active');
        if ( (lang === 'ru' && btn.textContent === 'RU') ||
             (lang === 'en' && btn.textContent === 'EN') ||
             (lang === 'de' && btn.textContent === 'DE') ) {
             btn.classList.add('active');
        }
    });
    
    const currentTranslations = translations[lang];
    if (!currentTranslations) {
        console.error(`No translations found for language: ${lang}`);
        return;
    }

    document.querySelectorAll('[data-translate]').forEach(element => {
        const key = element.getAttribute('data-translate');
        const translation = currentTranslations[key];
        if (translation !== undefined) {
            if (element.tagName === 'INPUT' && element.type !== 'submit' && element.type !== 'button') {
                element.placeholder = translation;
            } else if (element.tagName === 'TEXTAREA') {
                element.placeholder = translation;
            } else if (element.tagName === 'BUTTON' && element.classList.contains('submit-btn')) {
                element.innerHTML = translation.replace(/<span class="spinner"><\/span> /g, ''); 
                element.setAttribute('aria-label', translation.replace(/<[^>]*>/g, '')); 
            } else { 
                element.innerHTML = translation;
            }
        }
    });
}

function changeLanguage(lang) {
  localStorage.setItem('lang', lang);
  applyTranslations(lang);
  const readMoreBtn = document.querySelector('.read-more-btn');
  if (readMoreBtn) {
    const currentKey = readMoreBtn.getAttribute('data-translate'); 
    if (translations[lang] && translations[lang][currentKey]) {
        readMoreBtn.textContent = translations[lang][currentKey];
    }
  }
}

document.addEventListener('DOMContentLoaded', () => {
  const savedLang = localStorage.getItem('lang') || 'ru'; 
  applyTranslations(savedLang);
  if (typeof AOS !== "undefined") {
    AOS.init({
      duration: 800,
      once: true 
    });
  }
});